version: '2'
services:

  web:
      build: ./container/pushfor/nginx/centos7
      ports:
          - "8087:80"
      volumes:
          - .:/var/www/html/pushfor
          - ./container/pushfor/nginx/centos7/site.conf:/etc/nginx/conf.d/default.conf
      tty: true
      networks:
          - pushfor

  php-fpm:
      build: ./container/pushfor/php/php7
      ports:
          - "9000:9000"
      volumes:
          - .:/var/www/html/pushfor
          - ./container/pushfor/php/php7/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
          - ./container/pushfor/php/php7/php-fpm.conf:/etc/php-fpm.d/www.conf
      tty: true
      networks:
          - pushfor
      
networks:
    pushfor: