parameters:
    #parameter_name: value

services:
  pushfor.session.storage:
    class: AppBundle\Service\Storage\SessionStorage
    arguments: ['@session']

  pushfor.api.contact_request_validator:
    class: AppBundle\Service\Contact\Validator\ContactRequestValidator

  pushfor.api.new_contact_request_listener:
    class: AppBundle\EventListener\NewContactRequestListener
    arguments: ['@pushfor.session.storage']
    tags:
      - { name: kernel.event_listener, event: event.new.contact.request, method: onNewContactRequest }

  pushfor.api.contact_request_receive_listener:
      class: AppBundle\EventListener\ReceiveContactRequestListener
      arguments: ['@pushfor.session.storage']
      tags:
        - { name: kernel.event_listener, event: event.receive.contact.request, method: onNewContactRequestReceive }

  pushfor.api.message_sent_listener:
        class: AppBundle\EventListener\MessageSendListener
        arguments: ['@pushfor.session.storage']
        tags:
          - { name: kernel.event_listener, event: event.send.new.message, method: onNewMessageSent }

  pushfor.api.new_contact_request:
      class: AppBundle\Service\Contact\SendRequest
      arguments: ['@pushfor.api.contact_request_validator', '@event_dispatcher']

  pushfor.api.receive_contact_request:
      class: AppBundle\Service\Contact\ReceiveRequest
      arguments: ['@pushfor.api.contact_request_validator', '@event_dispatcher']

  pushfor.api.send_message:
      class: AppBundle\Service\Message\SendMessage
      arguments: ['@event_dispatcher']

  pushfor.api.read_message:
       class: AppBundle\Service\Message\ReadMessage
       arguments: ['@pushfor.session.storage']
