apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
        - name: nginx
          image: "puraskar/nginx:1.0.1"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "site-config"
              mountPath: "/etc/nginx/conf.d/default.conf"
      volumes:
        - name: site-config
          hostPath:
            path: "/home/puraskar/projects/pushfor/pfor-api/app/api/container/pushfor/nginx/centos7/site.conf"
