apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php-fpm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-fpm
        track: stable
    spec:
      containers:
        - name: php-fpm
          image: puraskar/php-fpm:1.0.1
#          volumeMounts:
#            - name: "../app/api"
#              mountPath: "/var/www/html/api"
#            - name: "../app/api/container/pushfor/php/php7/log.conf"
#              mountPath: "/usr/local/etc/php-fpm.d/zz-log.conf"
#            - name: "../app/api/container/pushfor/php/php7/php-fpm.conf"
#              mountPath: "/etc/php-fpm.d/www.conf"
